apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    uid: postgres_logs
    url: postgres:5432
    user: alexey
    password: admin
    database: logs
    secureJsonData:
      password: admin
    jsonData:
      database: logs
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
